"use client";
import { useEffect, useState } from "react";
type Health={ok?:boolean;version?:string;environment?:string;time?:string;database?:{ok?:boolean;provider?:string;latencyMs?:number};cloudJob?:Record<string,unknown>|null;scheduler?:Record<string,unknown>|null;error?:string};
type Status=Record<string,unknown>&{ok?:boolean;status?:string;percentage?:number;processed_symbols?:number;total_symbols?:number;remaining?:number;current_symbol?:string};
export default function CloudPage(){
 const [health,setHealth]=useState<Health>({}); const [status,setStatus]=useState<Status>({}); const [secret,setSecret]=useState(""); const [message,setMessage]=useState("");
 async function load(){const [h,s]=await Promise.all([fetch("/api/health",{cache:"no-store"}).then(r=>r.json()),fetch("/api/cloud/status",{cache:"no-store"}).then(r=>r.json())]);setHealth(h);setStatus(s);}
 useEffect(()=>{load();const id=setInterval(load,15000);return()=>clearInterval(id)},[]);
 async function call(path:string){setMessage("執行中…");const r=await fetch(path,{method:"POST",headers:{"x-cloud-admin-secret":secret,"content-type":"application/json"},body:"{}"});const j=await r.json();setMessage(j.ok?"完成":"失敗："+(j.error||"unknown"));load();}
 const cards=[["雲端網站",health.ok?"正常":"異常"],["資料庫",health.database?.ok?`Turso ${health.database.latencyMs??"—"}ms`:"異常"],["版本",health.version??"—"],["環境",health.environment??"—"],["每日任務",String(status.status??"尚未啟動")],["更新進度",`${status.percentage??0}%`],["已處理",`${status.processed_symbols??0}/${status.total_symbols??0}`],["目前股票",status.current_symbol??"—"]];
 return <main style={{maxWidth:1120,margin:"0 auto",padding:"clamp(16px,4vw,32px)",color:"#e2e8f0"}}><h1 style={{fontSize:"clamp(26px,5vw,42px)"}}>M7.8 雲端運作中心</h1><p>Mac 關機後，Vercel、Turso 與 Daily Cron 仍持續運作；手機可直接查看狀態。</p><section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(150px,1fr))",gap:12}}>{cards.map(([a,b])=><div key={String(a)} style={{background:"#0f172a",padding:18,borderRadius:14,border:"1px solid #334155"}}><small>{a}</small><div style={{fontSize:20,fontWeight:800,marginTop:8}}>{String(b)}</div></div>)}</section>{!health.ok&&<p style={{marginTop:16,padding:12,background:"#4c0519",borderRadius:10}}>⚠ 雲端健康檢查失敗：{health.error??"請查看監控紀錄"}</p>}<section style={{marginTop:20,background:"#0f172a",padding:18,borderRadius:14}}><h2>管理操作</h2><input type="password" placeholder="CLOUD_ADMIN_SECRET" value={secret} onChange={e=>setSecret(e.target.value)} style={{padding:12,width:"min(100%,360px)",marginBottom:10}}/><div style={{display:"flex",gap:10,flexWrap:"wrap"}}><button onClick={()=>call("/api/cloud/start")} style={{padding:12}}>建立今日任務</button><button onClick={()=>call("/api/cloud/worker")} style={{padding:12}}>執行下一批</button><button onClick={load} style={{padding:12}}>重新整理</button></div><p>{message}</p></section><p style={{opacity:.7}}>健康檢查時間：{health.time?new Date(health.time).toLocaleString("zh-TW"):"—"}</p></main>}
