"use client";
import { useCallback, useEffect, useMemo, useState } from "react";

type Quote={symbol:string;displayName:string;category:string;quoteDate:string;close:number|null;changePct:number|null;currency:string|null};
type Row={rank:number;symbol:string;stockName:string;tradeDate:string;close:number|null;totalScore:number;rawScore:number;marketFactor:number;trendScore:number;momentumScore:number;volumeScore:number;riskScore:number;confidence:number;recommendation:string;target1:number|null;target2:number|null;stopLoss:number|null;expectedReturn:number|null;riskReward:number|null;reasons:string[]};
type Payload={ok:boolean;error?:string;database:{provider:string;status:string;latencyMs:number};pipeline:{status:string;stage:string;total:number;processed:number;success:number;failed:number;currentSymbol:string|null;percentage:number;etaSeconds:number;updatedAt:string|null};summary:{analyzedCount:number;latestTradeDate:string|null;top30Count:number};market:{quotes:Quote[];regime:any};validation:{samples:number;active:number;completed:number;wins:number;winRate:number;averageReturn:number;averageMaxGain:number;averageMaxDrawdown:number};rows:Row[]};
type HotRow={symbol:string;stockName:string;market:string;source:string;reason:string|null;status:string;error:string|null;addedAt:string;analyzedAt:string|null;tradeDate:string|null;close:number|null;rawScore:number|null;marketAdjustment:number|null;finalScore:number|null;trendScore:number|null;momentumScore:number|null;volumeScore:number|null;riskScore:number|null;confidence:number|null;recommendation:string|null;target1:number|null;target2:number|null;stopLoss:number|null;expectedReturn:number|null;riskReward:number|null;reasons:string[]};
const money=(v:number|null)=>v==null?"—":v.toLocaleString("zh-TW",{maximumFractionDigits:2});
const pct=(v:number|null)=>v==null?"—":`${v>=0?"+":""}${v.toFixed(2)}%`;
function eta(s:number){if(!s)return"—";if(s<60)return`${s} 秒`;const m=Math.ceil(s/60);return m<60?`${m} 分鐘`:`${Math.floor(m/60)} 小時 ${m%60} 分`;}
export default function Dashboard(){const [data,setData]=useState<Payload|null>(null);const [error,setError]=useState("");const [busy,setBusy]=useState("");const [testSymbols,setTestSymbols]=useState<Set<string>>(new Set());const [selected,setSelected]=useState<Row|null>(null);const [hotRows,setHotRows]=useState<HotRow[]>([]);const [hotSymbol,setHotSymbol]=useState("");const [hotReason,setHotReason]=useState("");const [hotOpen,setHotOpen]=useState(false);
 const load=useCallback(async()=>{try{const r=await fetch('/api/m72/dashboard',{cache:'no-store'});const p=await r.json();if(!p.ok)throw new Error(p.error||'讀取失敗');setData(p);setError('');}catch(e){setError(e instanceof Error?e.message:String(e));}},[]);
 const loadTests=useCallback(async()=>{try{const r=await fetch('/api/portfolio/test-observation',{cache:'no-store'});const p=await r.json();if(p.ok)setTestSymbols(new Set((p.symbols||[]).map(String)));}catch{}},[]);
 const loadHot=useCallback(async()=>{try{const r=await fetch('/api/hot-stocks',{cache:'no-store'});const p=await r.json();if(!p.ok)throw new Error(p.error||'熱門股讀取失敗');setHotRows(p.rows||[]);}catch(e){setError(e instanceof Error?e.message:String(e));}},[]);
 useEffect(()=>{void load();void loadTests();void loadHot();const id=setInterval(()=>{void load();void loadHot();},10000);return()=>clearInterval(id)},[load,loadTests,loadHot]);
 async function action(name:string,url:string){setBusy(name);setError('');try{const r=await fetch(url,{method:'POST'});const p=await r.json();if(!p.ok)throw new Error(p.error||'操作失敗');await load();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy('')}}
 async function addHot(){const symbol=hotSymbol.trim();if(!symbol){setError('請輸入股票代號。');return;}setBusy('hot-add');setError('');try{const x=await fetch('/api/hot-stocks',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({symbol,reason:hotReason})});const p=await x.json();if(!p.ok)throw new Error(p.error||'加入失敗');setHotSymbol('');setHotReason('');setHotOpen(false);await loadHot();await analyzeHot(symbol);}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy('')}}
 async function analyzeHot(symbol:string){setBusy(`hot-${symbol}`);setError('');try{const x=await fetch('/api/hot-stocks/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({symbol})});const p=await x.json();if(!p.ok)throw new Error(p.error||'分析失敗');await Promise.all([loadHot(),load()]);}catch(e){setError(e instanceof Error?e.message:String(e));await loadHot();}finally{setBusy('')}}
 async function removeHot(symbol:string){setBusy(`remove-${symbol}`);setError('');try{const x=await fetch(`/api/hot-stocks?symbol=${encodeURIComponent(symbol)}`,{method:'DELETE'});const p=await x.json();if(!p.ok)throw new Error(p.error||'移除失敗');await loadHot();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy('')}}
 async function add(r:Row){setBusy(r.symbol);try{const x=await fetch('/api/portfolio/test-observation',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({symbol:r.symbol,buyPrice:r.close,buyDate:r.tradeDate})});const p=await x.json();if(!p.ok)throw new Error(p.error||'加入失敗');setTestSymbols(v=>new Set([...v,r.symbol]));}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy('')}}
 const progress=useMemo(()=>Math.max(0,Math.min(100,data?.pipeline.percentage??0)),[data]);const regime=data?.market?.regime;const marketScore=Number(regime?.market_score??0);const quotes=data?.market?.quotes??[];
 return <main style={{minHeight:'100vh',background:'#020617',color:'#e2e8f0',padding:'28px 18px'}}><div style={{maxWidth:1550,margin:'0 auto'}}>
 <header style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:16,flexWrap:'wrap'}}><div><div style={{color:'#22d3ee',fontWeight:900}}>Bruce&apos;s 台股決策中心 M7.4</div><h1 style={{margin:'8px 0'}}>市場環境 × Top 30 × AI 驗證</h1><p style={{color:'#94a3b8',margin:0}}>資料夾與網址維持不變；首頁新增全球市場環境與真實績效驗證。</p></div><div style={{display:'flex',gap:10,flexWrap:'wrap'}}><button style={purple} onClick={()=>setHotOpen(true)}>＋ 加入熱門股</button><button style={btn2} onClick={()=>void load()}>更新畫面</button><button style={btn} onClick={()=>action('market','/api/market/refresh')} disabled={!!busy}>{busy==='market'?'更新中…':'更新全球市場'}</button><button style={purple} onClick={()=>action('validation','/api/validation/refresh')} disabled={!!busy}>{busy==='validation'?'驗證中…':'更新 AI 驗證'}</button><button style={btn} onClick={()=>action('top30','/api/m72/top30/refresh')} disabled={!!busy}>{busy==='top30'?'排序中…':'重新排序 Top 30'}</button><a href="/daily-validation" style={link}>驗證中心</a></div></header>
 {error&&<div style={err}>{error}</div>}
 <section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(190px,1fr))',gap:12,marginTop:20}}><Card l="市場分數" v={regime?marketScore.toFixed(0):'—'} s={regime?`${regime.regime}｜風險 ${regime.risk_level}`:'尚未更新'}/><Card l="市場環境" v={regime?String(regime.regime):'—'} s={regime?`分數 ${Number(regime.market_score).toFixed(0)}｜${regime.risk_level}風險`:'尚未更新'}/><Card l="AI 驗證勝率" v={`${(data?.validation.winRate??0).toFixed(1)}%`} s={`${data?.validation.wins??0}/${data?.validation.completed??0} 已結案`}/><Card l="觀察池平均" v={`${(data?.validation.averageReturn??0).toFixed(2)}%`} s={`最大漲幅 ${(data?.validation.averageMaxGain??0).toFixed(2)}%`}/><Card l="Pipeline" v={`${progress.toFixed(1)}%`} s={`${data?.pipeline.processed??0}/${data?.pipeline.total??0}`}/><Card l="Top 30" v={String(data?.summary.top30Count??0)} s={data?.summary.latestTradeDate||'—'}/></section>
 <section style={panel}><div style={{display:'flex',justifyContent:'space-between',gap:12,flexWrap:'wrap'}}><div><h2 style={{margin:'0 0 6px'}}>全球市場環境</h2><div style={{color:'#94a3b8'}}>市場資料僅作風險調整，不取代個股分析。</div></div>{regime&&<div style={{textAlign:'right'}}><b style={{fontSize:22,color:marketScore>=60?'#4ade80':marketScore<40?'#fb7185':'#facc15'}}>{regime.regime}</b><div style={{color:'#94a3b8'}}>信心 {Number(regime.confidence).toFixed(0)}%</div></div>}</div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',gap:10,marginTop:16}}>{quotes.map(q=><div key={q.symbol} style={mini}><div style={{color:'#94a3b8',fontSize:12}}>{q.displayName}</div><div style={{fontWeight:900,fontSize:18,marginTop:6}}>{money(q.close)}</div><div style={{color:(q.changePct??0)>=0?'#4ade80':'#fb7185',fontWeight:800}}>{pct(q.changePct)}</div></div>)}{!quotes.length&&<div style={{color:'#94a3b8'}}>按「更新全球市場」建立第一筆市場快照。</div>}</div></section>
 <section style={panel}><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',flexWrap:'wrap'}}><div><h2 style={{margin:'0 0 6px'}}>熱門股候選池</h2><div style={{color:'#94a3b8'}}>由使用者手動加入；使用與全市場相同的固定演算法評分，不保證進入 Top 30。</div></div><button style={purple} onClick={()=>setHotOpen(true)}>＋ 加入熱門股</button></div><div style={{overflowX:'auto',marginTop:14}}><table style={{width:'100%',borderCollapse:'collapse',fontSize:13}}><thead><tr>{['股票','來源／原因','狀態','收盤','原始分','市場調整','最終分','建議','目標一','停損','操作'].map(h=><th style={th} key={h}>{h}</th>)}</tr></thead><tbody>{hotRows.map(r=><tr key={r.symbol}><td style={td}><b>{r.symbol}</b> {r.stockName}</td><td style={td}><div>{r.source==='manual'?'手動加入':r.source}</div><small style={{color:'#64748b'}}>{r.reason||'—'}</small></td><td style={td}><span style={{color:r.status==='completed'?'#4ade80':r.status==='error'?'#fb7185':'#facc15'}}>{r.status==='completed'?'已完成':r.status==='processing'?'分析中':r.status==='error'?'錯誤':'等待分析'}</span>{r.error&&<div style={{color:'#fb7185',maxWidth:260,whiteSpace:'normal'}}>{r.error}</div>}</td><td style={td}>{money(r.close)}</td><td style={td}>{r.rawScore==null?'—':r.rawScore.toFixed(1)}</td><td style={{...td,color:(r.marketAdjustment??0)>=0?'#4ade80':'#fb7185'}}>{r.marketAdjustment==null?'—':`${r.marketAdjustment>=0?'+':''}${r.marketAdjustment.toFixed(2)}`}</td><td style={{...td,color:'#67e8f9',fontWeight:900}}>{r.finalScore==null?'—':r.finalScore.toFixed(1)}</td><td style={td}>{r.recommendation||'—'}</td><td style={{...td,color:'#4ade80'}}>{money(r.target1)}</td><td style={{...td,color:'#fb7185'}}>{money(r.stopLoss)}</td><td style={td}><div style={{display:'flex',gap:6}}><button style={{...small,background:'#0891b2'}} disabled={busy===`hot-${r.symbol}`} onClick={()=>analyzeHot(r.symbol)}>{busy===`hot-${r.symbol}`?'分析中…':'重新分析'}</button><button style={{...small,background:'#be123c'}} disabled={busy===`remove-${r.symbol}`} onClick={()=>removeHot(r.symbol)}>移除</button></div></td></tr>)}{!hotRows.length&&<tr><td style={{...td,color:'#94a3b8'}} colSpan={11}>尚未加入熱門股。可將新聞熱門、成交量熱門或你特別關注的股票加入獨立候選池。</td></tr>}</tbody></table></div></section>
 <section style={panel}><div style={{display:'flex',justifyContent:'space-between'}}><b>全市場分析進度</b><span>{progress.toFixed(2)}%｜ETA {eta(data?.pipeline.etaSeconds??0)}</span></div><div style={track}><div style={{...bar,width:`${progress}%`}}/></div><div style={{color:'#94a3b8',marginTop:8}}>狀態 {data?.pipeline.status||'idle'}｜階段 {data?.pipeline.stage||'waiting'}｜目前 {data?.pipeline.currentSymbol||'—'}</div></section>
 <section style={{...panel,overflowX:'auto'}}><h2>今日 Top 30</h2><table style={{width:'100%',borderCollapse:'collapse',fontSize:13}}><thead><tr>{['排名','股票','收盤','原始分','市場調整','最終分','趨勢','動能','量能','風險','建議','目標一','停損','分析','測試池'].map(h=><th style={th} key={h}>{h}</th>)}</tr></thead><tbody>{(data?.rows||[]).map(r=><tr key={r.symbol}><td style={td}>{r.rank}</td><td style={td}><b>{r.symbol}</b> {r.stockName}</td><td style={td}>{money(r.close)}</td><td style={td}>{r.rawScore.toFixed(1)}</td><td style={{...td,color:r.marketFactor>=0?'#4ade80':'#fb7185'}}>{r.marketFactor>=0?'+':''}{r.marketFactor.toFixed(2)}</td><td style={{...td,color:'#67e8f9',fontWeight:900}}>{r.totalScore.toFixed(1)}</td><td style={td}>{r.trendScore.toFixed(1)}</td><td style={td}>{r.momentumScore.toFixed(1)}</td><td style={td}>{r.volumeScore.toFixed(1)}</td><td style={td}>{r.riskScore.toFixed(1)}</td><td style={td}>{r.recommendation}</td><td style={{...td,color:'#4ade80'}}>{money(r.target1)}</td><td style={{...td,color:'#fb7185'}}>{money(r.stopLoss)}</td><td style={td}><button style={{...small,background:'#334155'}} onClick={()=>setSelected(r)}>查看理由</button></td><td style={td}><button style={{...small,background:testSymbols.has(r.symbol)?'#334155':'#7c3aed'}} disabled={testSymbols.has(r.symbol)||busy===r.symbol} onClick={()=>add(r)}>{testSymbols.has(r.symbol)?'已加入':busy===r.symbol?'加入中…':'加入測試池'}</button></td></tr>)}</tbody></table></section>
 {hotOpen&&<div style={overlay} onClick={()=>setHotOpen(false)}><div style={modal} onClick={e=>e.stopPropagation()}><div style={{display:'flex',justifyContent:'space-between',gap:12}}><div><div style={{color:'#c084fc',fontWeight:900}}>熱門股候選池</div><h2 style={{margin:'8px 0'}}>加入市場熱門股票</h2></div><button style={btn2} onClick={()=>setHotOpen(false)}>關閉</button></div><p style={{color:'#94a3b8'}}>輸入股票代號後，系統會補齊價格、計算技術指標、套用市場環境並產生評分。分析可能需要數秒至數十秒。</p><label style={label}>股票代號<input style={input} value={hotSymbol} onChange={e=>setHotSymbol(e.target.value.replace(/\D/g,''))} placeholder="例如 2344、6182、3491" maxLength={6}/></label><label style={label}>加入原因（選填）<input style={input} value={hotReason} onChange={e=>setHotReason(e.target.value)} placeholder="例如：成交量熱門、新聞題材、朋友推薦" maxLength={120}/></label><button style={{...purple,width:'100%',marginTop:14}} disabled={busy==='hot-add'} onClick={()=>addHot()}>{busy==='hot-add'?'加入並分析中…':'加入並立即分析'}</button></div></div>}
 {selected&&<div style={overlay} onClick={()=>setSelected(null)}><div style={modal} onClick={e=>e.stopPropagation()}><div style={{display:'flex',justifyContent:'space-between',gap:12}}><div><div style={{color:'#67e8f9',fontWeight:900}}>規則型演算法分析</div><h2 style={{margin:'8px 0'}}>{selected.symbol} {selected.stockName}</h2></div><button style={btn2} onClick={()=>setSelected(null)}>關閉</button></div><div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:10}}><Card l="原始分" v={selected.rawScore.toFixed(1)}/><Card l="市場調整" v={`${selected.marketFactor>=0?'+':''}${selected.marketFactor.toFixed(2)}`}/><Card l="最終分" v={selected.totalScore.toFixed(1)}/></div><h3>選入理由</h3><ol>{selected.reasons.map((reason,index)=><li key={`${reason}-${index}`} style={{marginBottom:8,color:'#cbd5e1'}}>{reason}</li>)}</ol><div style={{color:'#94a3b8',fontSize:13}}>本頁 100% 由固定公式與規則計算，不會呼叫 ChatGPT 或其他大型語言模型。</div></div></div>}
 </div></main>}
function Card({l,v,s}:{l:string;v:string;s?:string}){return <div style={card}><small style={{color:'#94a3b8'}}>{l}</small><div style={{fontSize:26,fontWeight:900,marginTop:8}}>{v}</div>{s&&<div style={{color:'#64748b',fontSize:13,marginTop:6}}>{s}</div>}</div>}
const label={display:'grid',gap:7,marginTop:14,fontWeight:800,color:'#cbd5e1'} as const;const input={background:'#020617',border:'1px solid #334155',borderRadius:10,padding:'12px 13px',color:'#e2e8f0',fontSize:16} as const;const overlay={position:'fixed',inset:0,background:'rgba(2,6,23,.82)',display:'grid',placeItems:'center',padding:18,zIndex:50} as const;const modal={width:'min(760px,96vw)',maxHeight:'88vh',overflowY:'auto',background:'#0f172a',border:'1px solid #334155',borderRadius:18,padding:22} as const;const panel={background:'#0f172a',border:'1px solid #243244',borderRadius:16,padding:18,marginTop:16} as const;const card={background:'#0f172a',border:'1px solid #243244',borderRadius:14,padding:16} as const;const mini={background:'#020617',border:'1px solid #243244',borderRadius:12,padding:12} as const;const track={height:10,background:'#1e293b',borderRadius:999,overflow:'hidden',marginTop:12} as const;const bar={height:'100%',background:'linear-gradient(90deg,#22c55e,#06b6d4)'} as const;const th={textAlign:'left',padding:'10px 8px',borderBottom:'1px solid #334155',color:'#94a3b8',whiteSpace:'nowrap'} as const;const td={padding:'11px 8px',borderBottom:'1px solid #1e293b',whiteSpace:'nowrap'} as const;const btn={background:'#0891b2',color:'white',border:0,borderRadius:9,padding:'11px 16px',fontWeight:800,cursor:'pointer'} as const;const btn2={...btn,background:'#334155'} as const;const purple={...btn,background:'#7c3aed'} as const;const link={...btn,textDecoration:'none',background:'#2563eb'} as const;const small={...btn,padding:'7px 10px'} as const;const err={padding:14,border:'1px solid #be123c',background:'#4c0519',color:'#fecdd3',borderRadius:12,marginTop:16} as const;
