"use client";
import { useCallback, useEffect, useState } from "react";

type Row={snapshot_date:string;symbol:string;stock_name:string;buy_date:string;entry_price:number;current_price:number|null;return_pct:number|null;highest_price:number|null;lowest_price:number|null;target_1:number|null;target_2:number|null;stop_loss:number|null;result_status:string;market_score:number|null;market_regime:string|null;ai_score:number|null;confidence:number|null;holding_days:number;trading_days:number;max_gain_pct:number|null;max_drawdown_pct:number|null;entry_market_score:number|null;entry_market_regime:string|null;entry_ai_score:number|null;algorithm_version:string|null};
type Payload={ok:boolean;error?:string;summary:{samples:number;active:number;completed:number;wins:number;winRate:number;averageReturn:number;averageMaxGain:number;averageMaxDrawdown:number};rows:Row[]};
const money=(v:number|null)=>v==null?"—":Number(v).toLocaleString("zh-TW",{maximumFractionDigits:2});
export default function ValidationCenter(){const [data,setData]=useState<Payload|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState("");
 const load=useCallback(async()=>{try{const r=await fetch('/api/validation/status',{cache:'no-store'});const p=await r.json();if(!p.ok)throw new Error(p.error||'讀取失敗');setData(p);setError('');}catch(e){setError(e instanceof Error?e.message:String(e));}},[]);
 useEffect(()=>{void load();},[load]);
 async function refresh(){setBusy(true);try{const r=await fetch('/api/validation/refresh',{method:'POST'});const p=await r.json();if(!p.ok)throw new Error(p.error||'更新失敗');await load();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
 return <main style={{minHeight:'100vh',background:'#020617',color:'#e2e8f0',padding:'28px 18px'}}><div style={{maxWidth:1500,margin:'0 auto'}}><div style={{display:'flex',justifyContent:'space-between',gap:16,alignItems:'center',flexWrap:'wrap'}}><div><div style={{color:'#c084fc',fontWeight:900}}>Bruce&apos;s 台股決策中心 M7.4</div><h1>AI 驗證中心</h1><p style={{color:'#94a3b8'}}>追蹤測試觀察池的真實績效，並保留加入當下的市場環境與 AI 分數。</p></div><button onClick={refresh} disabled={busy} style={btn}>{busy?'更新中…':'更新今日驗證'}</button></div>{error&&<div style={err}>{error}</div>}
 <section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:12,marginTop:20}}><Card l="樣本" v={String(data?.summary.samples??0)}/><Card l="已結案" v={String(data?.summary.completed??0)}/><Card l="成功" v={String(data?.summary.wins??0)}/><Card l="勝率" v={`${(data?.summary.winRate??0).toFixed(1)}%`}/><Card l="追蹤中" v={String(data?.summary.active??0)}/><Card l="平均報酬" v={`${(data?.summary.averageReturn??0).toFixed(2)}%`}/><Card l="平均最大漲幅" v={`${(data?.summary.averageMaxGain??0).toFixed(2)}%`}/><Card l="平均最大回撤" v={`${(data?.summary.averageMaxDrawdown??0).toFixed(2)}%`}/></section>
 <section style={{...panel,overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',fontSize:13}}><thead><tr>{['股票','加入日','交易日','起始價','現價','報酬','最大漲幅','最大回撤','目標一','目標二','停損','加入市場','加入分數','演算法分數','結果'].map(h=><th key={h} style={th}>{h}</th>)}</tr></thead><tbody>{(data?.rows||[]).map(r=><tr key={`${r.snapshot_date}-${r.symbol}`}><td style={td}><b>{r.symbol}</b> {r.stock_name}</td><td style={td}>{r.buy_date}</td><td style={td}>{r.trading_days??r.holding_days}</td><td style={td}>{money(r.entry_price)}</td><td style={td}>{money(r.current_price)}</td><td style={{...td,color:(r.return_pct??0)>=0?'#4ade80':'#fb7185'}}>{r.return_pct==null?'—':`${Number(r.return_pct).toFixed(2)}%`}</td><td style={{...td,color:'#4ade80'}}>{r.max_gain_pct==null?'—':`${Number(r.max_gain_pct).toFixed(2)}%`}</td><td style={{...td,color:'#fb7185'}}>{r.max_drawdown_pct==null?'—':`${Number(r.max_drawdown_pct).toFixed(2)}%`}</td><td style={td}>{money(r.target_1)}</td><td style={td}>{money(r.target_2)}</td><td style={td}>{money(r.stop_loss)}</td><td style={td}>{r.entry_market_regime||r.market_regime||'—'}</td><td style={td}>{r.entry_market_score==null?'—':Number(r.entry_market_score).toFixed(1)}</td><td style={td}>{r.entry_ai_score==null?(r.ai_score==null?'—':Number(r.ai_score).toFixed(1)):Number(r.entry_ai_score).toFixed(1)}</td><td style={td}>{r.result_status}</td></tr>)}</tbody></table>{!data?.rows?.length&&<p style={{color:'#94a3b8'}}>尚無驗證資料。先在 Top 30 加入測試池，再按「更新今日驗證」。</p>}</section></div></main>}
function Card({l,v}:{l:string;v:string}){return <div style={card}><small style={{color:'#94a3b8'}}>{l}</small><div style={{fontSize:26,fontWeight:900,marginTop:8}}>{v}</div></div>}
const panel={background:'#0f172a',border:'1px solid #243244',borderRadius:16,padding:18,marginTop:16} as const;const card={...panel,marginTop:0} as const;const th={textAlign:'left',padding:'10px 8px',borderBottom:'1px solid #334155',color:'#94a3b8',whiteSpace:'nowrap'} as const;const td={padding:'11px 8px',borderBottom:'1px solid #1e293b',whiteSpace:'nowrap'} as const;const btn={background:'#7c3aed',color:'white',border:0,borderRadius:9,padding:'11px 16px',fontWeight:800,cursor:'pointer'} as const;const err={padding:14,border:'1px solid #be123c',background:'#4c0519',color:'#fecdd3',borderRadius:12,marginTop:16} as const;
